services:
  frontend-react-js:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/frontend/src
      - /frontend/node_modules
    # environment:
    command:
      npm run dev
